services:
  backend:
    build:
      context: https://github.com/LuisCastelblanco/TaskTracker.git#main
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:cheo2001@db:5432/tasktracker
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: https://github.com/LuisCastelblanco/taskmanager.git#main
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cheo2001
      - POSTGRES_DB=tasktracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge